apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-atom-iam-user-policy-attachment-aws
  description: "Terraform atom: AWS IAM User Policy Attachment - attaches a managed policy to an IAM user"
  annotations:
    github.com/project-slug: PlatformStackPulse/tf-atom-iam-user-policy-attachment-aws
    backstage.io/techdocs-ref: dir:.
  tags: [terraform, aws, atom, iam]
  links:
    - url: https://github.com/PlatformStackPulse/tf-atom-iam-user-policy-attachment-aws
      title: GitHub Repository
      icon: github
spec:
  type: terraform-module
  lifecycle: production
  owner: platform-team
  system: terraform-atoms
